language: node_js
node_js:
  - "node"

cache: npm

script:
  - npm run test:unit
  - npm run build
  - cp bakedresults/*.json dist/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: dist # folder to upload
  repo: npoirey/npoirey.github.io
  target_branch: master
  on:
    branch: master